blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/orgs/GENeSYS-MOD/discussions
    about: Please use our GitHub Discussions page for questions and general ideas. :)